complete --command sgpt --exclusive
complete --command sgpt --exclusive --long model --arguments "gpt-3.5-turbo gpt-4 gpt-4-32" --description 'OpenAI GPT model to use.'
complete --command sgpt --exclusive --long temperature --arguments "(seq 0.0 0.1 2.0)" --description 'Randomness of generated output.'
complete --command sgpt --exclusive --long top-probability --arguments "(seq 0.0 0.1 1.0)" --description 'Limits highest probable tokens (words).'
complete --command sgpt --exclusive --long editor --description 'Open $EDITOR to provide a prompt.'
complete --command sgpt --exclusive --long no-cache --description 'Do not cache completion results.'
complete --command sgpt --exclusive --long help --description 'Show help message and exit.'
complete --command sgpt --exclusive --short s --long shell --description 'Generate and execute shell commands.'
complete --command sgpt --exclusive --short d --long describe-shell --description 'Describe a shell command.'
complete --command sgpt --exclusive --long code --description 'Generate only code.'
complete --command sgpt --exclusive --long chat --description 'Follow conversation with id, use temp for quick session.'
complete --command sgpt --exclusive --long repl --description 'Start a REPL (Read-eval-print loop) session.'
complete --command sgpt --exclusive --long show-chat --description 'Show all messages from provided chat id.'
complete --command sgpt --exclusive --long list-chats --description 'List all existing chat ids.'
complete --command sgpt --exclusive --long role --description 'System role for GPT model.'
complete --command sgpt --exclusive --long create-role --description 'Create role.'
complete --command sgpt --exclusive --long show-role --description 'Show role.'
complete --command sgpt --exclusive --long list-roles --description 'List roles.'
